The file loaded in below is an export from the TruckDevices Dynamo table. Prior to export the table was filtered only for active trucks, i.e.:
- device_imei exists
- valid_to does not exist

We only filter for active trucks (and records) as we would like the most up-to-date information on imei to CB (based on the serial_no) assignments to be able to check for duplicates

In [ ]:
import pandas as pd

truck_devices = pd.read_csv('20250210_active_trucks_truckdevices_dynamo_export.csv')

In [9]:
truck_devices.head()

,truck_id,valid_from,calibration_id,config,device_imei,drum_volume,extra_info,foo,gearbox_ratio,imsi,...,port_a_offset_volts,port_b_offset_volts,pressure_sensor_offset_volts,pressure_sensor_range_bar,pressure_sensor_range_volts,project,registration,rmc_provider,serial_no,vin
0,251,2025-01-29 10:54:11.635,NaN,"{""charging_direction"":{""S"":""counter_clockwise""...",356129320196170,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,GR863HT,Holcim,20300454,NaN
1,187,2024-12-02 16:58:19.401,NaN,"{""charging_direction"":{""S"":""clockwise""},""opera...",359206105981047,8.0,NaN,bar,120.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,RX14TCV,Cemex,20300118,NaN
2,154,2024-12-02 16:06:47.308,NaN,"{""charging_direction"":{""S"":""clockwise""},""opera...",359206100851666,8.0,NaN,bar,120.3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,EG66NTJ,Cemex,20300026,NaN
3,512,2025-01-24 18:08:15.766,NaN,"{""charging_direction"":{""S"":""clockwise""},""opera...",356129320140301,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,GJ67RZC,London-Concrete,20300578,NaN
4,286,2025-01-06 10:12:33.315,NaN,"{""charging_direction"":{""S"":""clockwise""},""opera...",356129320102244,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,KX18KKF,Cemex,20300572,NaN

In [10]:
truck_devices.columns

Index(['truck_id', 'valid_from', 'calibration_id', 'config', 'device_imei',
       'drum_volume', 'extra_info', 'foo', 'gearbox_ratio', 'imsi',
       'motor_displacement_cm3', 'port_a_offset_volts', 'port_b_offset_volts',
       'pressure_sensor_offset_volts', 'pressure_sensor_range_bar',
       'pressure_sensor_range_volts', 'project', 'registration',
       'rmc_provider', 'serial_no', 'vin'],
      dtype='object')

In [11]:
truck_devices[['device_imei', 'serial_no']].groupby('serial_no').nunique().sort_values(by='device_imei', ascending=False).head(10)

           device_imei
serial_no
1234TEST             1
20300397             1
20300408             1
20300407             1
20300406             1
20300405             1
20300402             1
20300401             1
20300400             1
20300399             1

No duplicate imei assignments found for any CBs